### ISSUE TITLE
README example is malformed

### ISSUE THREAD

**Issue by daemianmack** [luchiniatwork/migrana#1]
Hey, just a heads-up, the README `tx-fn` example from Conformity is mal-formed -- I [recently updated the original](https://github.com/rkneufeld/conformity/pull/43) and you might want to do something similar to avoid a confusing experience. :)

Obviously it's early days but I look forward to having a wider selection of Datomic tools to choose from!

**Comment by luchiniatwork** [comment]
Thanks @daemianmack ... I shamelessly copied your example without much thought. I'll update it with something much simpler for the first release.

**Comment by daemianmack** [comment]
No worries! I must have pasted it into the README without verifying it in a REPL -- the timebomb that keeps on giving.

**Comment by luchiniatwork** [comment]
Closed by #2 for now
